version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_catalog_db:/data/db
    ports:
      - 27017:27017

  authenticatedb:
    image: mongo
    container_name: authenticatedb
    restart: always
    volumes:
      - mongo_authenticate_db:/data/db
    ports:
      - 27018:27017

  usersdb:
    image: mongo
    container_name: usersdb
    restart: always
    volumes:
      - mongo_users_db:/data/db
    ports:
      - 27019:27017

  discountsdb:
    image: mongo
    container_name: discountsdb
    restart: always
    volumes:
      - mongo_discounts_db:/data/db
    ports:
      - 27020:27017

  basketdb:
    image: mongo
    container_name: basketdb
    restart: always
    volumes:
      - mongo_basket_db:/data/db
    ports:
      - 27021:27017
  
  catalog.api:
    image: tshop-catalog-img:latest
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabaseSettings:ConnectionString=mongodb://catalogdb:27017
      - ASPNETCORE_URLS=https://+:443;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ssl123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalogdb
    ports:
      - 8000:443
    volumes:
      - ./https:/https:ro 
  
  authenticate.api:
    image: tshop-authenticate-img:latest
    container_name: authenticateapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthenticateDatabaseSettings:ConnectionString=mongodb://authenticatedb:27017
      - GrpcService:User:UserApiUrl=https://usersapi:443
    depends_on:
      - authenticatedb
    ports:
      - 8001:80 
  
  users.api:
    image: tshop-users-img:latest
    container_name: usersapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UserDatabaseSettings:ConnectionString=mongodb://usersdb:27017
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ssl123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - usersdb
    ports:
      - 8002:80
      - 8003:443
    volumes:
      - ./https:/https:ro 
  
  discounts.api:
    image: tshop-discounts-img:latest
    container_name: discountsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DiscountDatabaseSettings:ConnectionString=mongodb://discountsdb:27017
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ssl123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - discountsdb
    ports:
      - 8004:443
    volumes:
      - ./https:/https:ro 
  
  basketapi.api:
    image: tshop-basket-img:latest
    container_name: basketapiapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BasketDatabaseSettings:ConnectionString=mongodb://basketdb:27017
      - GrpcService:Catalog:CatalogApiUrl=https://catalogapi:443
      - GrpcService:Discount:DiscountApiUrl=https://discountsapi:443
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ssl123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basketdb
    ports:
      - 8005:443
    volumes:
      - ./https:/https:ro 

volumes:
  mongo_catalog_db:
  mongo_authenticate_db:
  mongo_users_db:
  mongo_discounts_db:
  mongo_basket_db: