version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
  
  catalog.api:
    image: tshop-catalog-img:latest
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
      - 8000:80

volumes:
  mongodb: